"""empty message

Revision ID: 0cc72f7b4f30
Revises: b912b7cca25a
Create Date: 2022-11-05 20:28:27.754896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cc72f7b4f30'
down_revision = 'b912b7cca25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prova', 'tempo',
               existing_type=mysql.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prova', 'tempo',
               existing_type=sa.Text(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
