"""add_turma_prova

Revision ID: 1eaae9bc7bd0
Revises: 2950181ccb2a
Create Date: 2021-07-02 19:48:34.112460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eaae9bc7bd0'
down_revision = '2950181ccb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prova', sa.Column('turma', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prova', 'turma', ['turma'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prova', type_='foreignkey')
    op.drop_column('prova', 'turma')
    # ### end Alembic commands ###
