"""nota

Revision ID: 1f5579ceb4b8
Revises: 5794bf02db7d
Create Date: 2021-07-03 11:23:04.160738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f5579ceb4b8'
down_revision = '5794bf02db7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno_prova', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('aluno_prova', sa.Column('nota', sa.Integer(), nullable=False))
    op.alter_column('aluno_prova', 'aluno_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('aluno_prova', 'prova_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('aluno_prova_ibfk_2', 'aluno_prova', type_='foreignkey')
    op.drop_constraint('aluno_prova_ibfk_1', 'aluno_prova', type_='foreignkey')
    op.create_foreign_key(None, 'aluno_prova', 'prova', ['prova_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aluno_prova', 'aluno', ['aluno_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aluno_prova', type_='foreignkey')
    op.drop_constraint(None, 'aluno_prova', type_='foreignkey')
    op.create_foreign_key('aluno_prova_ibfk_1', 'aluno_prova', 'aluno', ['aluno_id'], ['id'])
    op.create_foreign_key('aluno_prova_ibfk_2', 'aluno_prova', 'prova', ['prova_id'], ['id'])
    op.alter_column('aluno_prova', 'prova_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('aluno_prova', 'aluno_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('aluno_prova', 'nota')
    op.drop_column('aluno_prova', 'id')
    # ### end Alembic commands ###
