"""empty message

Revision ID: 293bea2f2739
Revises: 0cc72f7b4f30
Create Date: 2022-11-05 20:53:09.418474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '293bea2f2739'
down_revision = '0cc72f7b4f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno_prova', sa.Column('data_entrega', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('prova', 'tempo',
               existing_type=mysql.TEXT(),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prova', 'tempo',
               existing_type=sa.Date(),
               type_=mysql.TEXT(),
               nullable=True)
    op.drop_column('aluno_prova', 'data_entrega')
    # ### end Alembic commands ###
