"""relaciona_aluno_turma

Revision ID: 2950181ccb2a
Revises: 
Create Date: 2021-07-02 19:15:16.027129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2950181ccb2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno_na_turma',
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], )
    )
    op.drop_constraint('turma_ibfk_1', 'turma', type_='foreignkey')
    op.create_foreign_key(None, 'turma', 'professor', ['id_professor'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turma', type_='foreignkey')
    op.create_foreign_key('turma_ibfk_1', 'turma', 'usuario', ['id_professor'], ['id'], ondelete='CASCADE')
    op.drop_table('aluno_na_turma')
    # ### end Alembic commands ###
