"""add_provas

Revision ID: 5794bf02db7d
Revises: 1eaae9bc7bd0
Create Date: 2021-07-02 20:37:03.377804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5794bf02db7d'
down_revision = '1eaae9bc7bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno_prova',
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['prova_id'], ['prova.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aluno_prova')
    # ### end Alembic commands ###
