"""empty message

Revision ID: b912b7cca25a
Revises: bcac38b19c75
Create Date: 2022-11-05 20:19:24.830405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b912b7cca25a'
down_revision = 'bcac38b19c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prova', sa.Column('tempo', sa.DateTime(), nullable=True))
    op.add_column('prova', sa.Column('temporizada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prova', 'temporizada')
    op.drop_column('prova', 'tempo')
    # ### end Alembic commands ###
